export const ELEMENTS = {
  numero0: '[colspan="2"] > .botao',
  numero1: ":nth-child(4) > :nth-child(1) > .botao",
  numero2: ":nth-child(4) > :nth-child(2) > .botao",
  numero3: ":nth-child(4) > :nth-child(3) > .botao",
  numero4: ":nth-child(3) > :nth-child(1) > .botao",
  numero5: ":nth-child(3) > :nth-child(2) > .botao",
  numero6: ":nth-child(3) > :nth-child(3) > .botao",
  numero7: ":nth-child(2) > :nth-child(1) > .botao",
  numero8: ":nth-child(2) > :nth-child(2) > .botao",
  numero9: ":nth-child(2) > :nth-child(3) > .botao",
  botaoDeMultiplicacao: ":nth-child(1) > :nth-child(4) > .botao",
  botaoDeDivisao: ":nth-child(1) > :nth-child(3) > .botao",
  botaoDeSubtracao: ":nth-child(2) > :nth-child(4) > .botao",
  botaoDeAdicao: ":nth-child(3) > :nth-child(4) > .botao",
  botaoQueApagaTodosOsNumeros: ":nth-child(1) > :nth-child(1) > .botao",
  botaoQueApagaUltimoNumeroDigitado: ":nth-child(1) > :nth-child(2) > .botao",
  botaoQueCalculaResultado: '[rowspan="2"] > .botao',
  inputResultado: "#resultado",
}
